source 'https://rubygems.org'

# 0.5 speaks Bolt 5 (0.3 misreads nodes from Neo4j 5) and needs Ruby 3.4
gem 'neo4j_bolt', '0.5.0'
# playtest.rb pdf: the printed feedback of the classroom playtesting
gem 'prawn'
# its QR code: the game to open
gem 'rqrcode_core'
gem 'chunky_png'
gem 'faye-websocket', '~> 0.12.0'
gem 'rerun'
gem 'ruby-vips'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'
